package com.tenant.mapper;

import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

import com.tenant.dto.request.AddTenantRequestDto;
import com.tenant.entity.TenantsDBDetails;

@Mapper(componentModel = "spring")
public interface TenantsDBDetailsMapper {

    /**
     * Maps AddTenantRequestDto → TenantsDBDetails entity.
     * tenantId is auto-generated by the DB, so it is ignored.
     * Audit fields are managed by Auditable / JPA listeners.
     * Default values (dbPort, status, type, timezone, locale) defined on
     * the entity via @Builder.Default are preserved by ignoring them here
     * when they are null in the request — MapStruct will leave the field
     * at whatever the entity initialiser sets.
     */
    @Mapping(target = "tenantId",         ignore = true)
    TenantsDBDetails toEntity(AddTenantRequestDto request);
}
