package com.employee.enums;

public enum FieldDefinitionKey {

	FIRST_NAME,ADDRESS,BOOLEAN,CHECKBOX,CURRENCY,DATE,DATE_OF_BIRTH,DATETIME,DECIMAL,
	DEPARTMENT,EMPLOYEE,DROPDOWN,EMIAL,FILE,GENDER,LAST_NAME,MOBILE,MULTI_SELECT,NAME,
	NUMBER,RADIO,TEXTAREA,TIME,URL,OTHER
}
