spring.application.name=api-gateway

#server.address=172.20.1.57
server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/


eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true


# ==========================================
# AUTH SERVICE
# ==========================================

spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/auth/**

# ==========================================
# TENANT SERVICE
# ==========================================

spring.cloud.gateway.routes[1].id=tenant-service
spring.cloud.gateway.routes[1].uri=lb://TENANT-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/tenant/**

# CORS
cors.allowedOrigins=http://localhost:3000,http://localhost:5173,http://localhost:5173/hrms,http://172.20.1.46,http://172.20.1.190,http://localhost:5174,http://localhost:5174/hrms


